"""empty message

Revision ID: 22d8d4f3cb3d
Revises: e9efb0a48bb6
Create Date: 2021-05-29 02:15:24.283974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d8d4f3cb3d'
down_revision = 'e9efb0a48bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_record', 'phone_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_record', sa.Column('phone_no', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
