"""empty message

Revision ID: 45453df2d83e
Revises: 5c5dbb08cdc1
Create Date: 2021-05-28 19:52:28.023228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45453df2d83e'
down_revision = '5c5dbb08cdc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'password')
    # ### end Alembic commands ###
