"""empty message

Revision ID: cdbc1a2fd5ae
Revises: 22d8d4f3cb3d
Create Date: 2021-05-29 02:18:21.560198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbc1a2fd5ae'
down_revision = '22d8d4f3cb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_record', 'medical_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('medical_record', 'record_owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_record', 'record_owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('medical_record', 'medical_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
